version: "3.9"

services:
  backend:
    build: ./minerdata-backend
    container_name: backend
    ports:
      - "3001:3001"
    env_file:
      - ./minerdata-backend/.env
    volumes:
      - ./minerdata-backend:/app
    networks:
      - minerdata-net
    depends_on:
      - db

  frontend:
    build: ./minerdata-frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./minerdata-frontend:/app
    environment:
      - VITE_BACKEND_URL=http://backend:3001
    networks:
      - minerdata-net
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: minerdata-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: minerdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - minerdata-net

networks:
  minerdata-net:
    driver: bridge

volumes:
  postgres-data:
