version: "3.9"

services:
  backend:
    build: ./minerdata-backend
    container_name: minerdata-backend
    ports:
      - "3001:3001"
    env_file:
      - ./minerdata-backend/.env
    volumes:
      - ./minerdata-backend:/app
    networks:
      - minerdata-net

  frontend:
    build: ./minerdata-frontend
    container_name: minerdata-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./minerdata-frontend:/app
    environment:
      - VITE_BACKEND_URL=http://backend:3001
    networks:
      - minerdata-net
    depends_on:
      - backend

networks:
  minerdata-net:
    driver: bridge
